{% set version = '0.5.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-theft
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/theft_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/theft/theft_{{ version }}.tar.gz
  sha256: 7acfe66dcbd373dce73a928fe293ccb2392be86f67f7943ef1a5dc0c65c6359a

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-r.matlab
    - r-rcatch22
    - r-rtsne
    - r-broom
    - r-dplyr
    - r-e1071
    - r-fabletools
    - r-feasts
    - r-ggplot2
    - r-janitor
    - r-purrr
    - r-reshape2
    - r-reticulate
    - r-rlang
    - r-scales
    - r-tibble
    - r-tidyr
    - r-tsfeatures
    - r-tsibble

  run:
    - r-base
    - r-r.matlab
    - r-rcatch22
    - r-rtsne
    - r-broom
    - r-dplyr
    - r-e1071
    - r-fabletools
    - r-feasts
    - r-ggplot2
    - r-janitor
    - r-purrr
    - r-reshape2
    - r-reticulate
    - r-rlang
    - r-scales
    - r-tibble
    - r-tidyr
    - r-tsfeatures
    - r-tsibble

test:
  commands:
    - $R -e "library('theft')"           # [not win]
    - "\"%R%\" -e \"library('theft')\""  # [win]

about:
  home: https://hendersontrent.github.io/theft/
  license: MIT
  summary: Consolidates and calculates different sets of time-series features from multiple 'R'
    and 'Python' packages including 'Rcatch22' Henderson, T. (2021) <doi:10.5281/zenodo.5546815>,
    'feasts' O'Hara-Wild, M., Hyndman, R., and Wang, E. (2021) <https://CRAN.R-project.org/package=feasts>,
    'tsfeatures' Hyndman, R., Kang, Y., Montero-Manso, P., Talagala, T., Wang, E., Yang,
    Y., and O'Hara-Wild, M. (2020) <https://CRAN.R-project.org/package=tsfeatures>,
    'tsfresh' Christ, M., Braun, N., Neuffer, J., and Kempa-Liehr A.W. (2018) <doi:10.1016/j.neucom.2018.03.067>,
    'TSFEL' Barandas, M., et al. (2020) <doi:10.1016/j.softx.2020.100456>, and 'Kats'
    Facebook Infrastructure Data Science (2021) <https://facebookresearch.github.io/Kats/>.
    Provides a standardised workflow from feature calculation to feature processing,
    machine learning classification procedures, and the production of statistical graphics.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# The original CRAN metadata for this package was:

# Package: theft
# Type: Package
# Title: Tools for Handling Extraction of Features from Time Series
# Version: 0.5.3
# Date: 2023-08-11
# Authors@R: c( person("Trent", "Henderson", email = "then6675@uni.sydney.edu.au", role = c("cre", "aut")), person("Annie", "Bryant", role = "ctb", comment = "Balanced classification accuracy") )
# Maintainer: Trent Henderson <then6675@uni.sydney.edu.au>
# Description: Consolidates and calculates different sets of time-series features from multiple 'R' and 'Python' packages including 'Rcatch22' Henderson, T. (2021) <doi:10.5281/zenodo.5546815>, 'feasts' O'Hara-Wild, M., Hyndman, R., and Wang, E. (2021) <https://CRAN.R-project.org/package=feasts>, 'tsfeatures' Hyndman, R., Kang, Y., Montero-Manso, P., Talagala, T., Wang, E., Yang, Y., and O'Hara-Wild, M. (2020) <https://CRAN.R-project.org/package=tsfeatures>, 'tsfresh' Christ, M., Braun, N., Neuffer, J., and Kempa-Liehr A.W. (2018) <doi:10.1016/j.neucom.2018.03.067>, 'TSFEL' Barandas, M., et al. (2020) <doi:10.1016/j.softx.2020.100456>, and 'Kats' Facebook Infrastructure Data Science (2021) <https://facebookresearch.github.io/Kats/>. Provides a standardised workflow from feature calculation to feature processing, machine learning classification procedures, and the production of statistical graphics.
# BugReports: https://github.com/hendersontrent/theft/issues
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.5.0)
# Imports: rlang, stats, dplyr, ggplot2, tidyr, reshape2, scales, tibble, purrr, broom, tsibble, fabletools, tsfeatures, feasts, Rcatch22, reticulate, Rtsne, R.matlab, e1071, janitor
# Suggests: lifecycle, cachem, bslib, knitr, markdown, rmarkdown, pkgdown, testthat
# RoxygenNote: 7.2.2
# VignetteBuilder: knitr
# URL: https://hendersontrent.github.io/theft/
# NeedsCompilation: no
# Packaged: 2023-08-11 12:10:55 UTC; User
# Author: Trent Henderson [cre, aut], Annie Bryant [ctb] (Balanced classification accuracy)
# Repository: CRAN
# Date/Publication: 2023-08-11 12:40:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
